### ISSUE TITLE
Bug with jquery.js sourcecode. Highlighting broken starting line 2356.

### ISSUE THREAD

**Issue by telegraphinho** [Benvie/JavaScriptNext.tmLanguage#68] opened 2015-01-18 14:29 UTC
jQuery version: 1.11.2(didn't check other versions)
Line #: 2356
Screenshot of the problem: http://i.imgur.com/H5eQJ70.png
It stumbles on this whole line(doesn't highlight any syntax for some reason) AND it doesn't highlight syntax in the subsequent lines unless you remove the ternary operator in the end(question mark and further till the closing curly bracket).

If you remove this whole line it also fixes the problem.

It works fine with regular Javascript Syntax. Any ideas as to what causes it?

**Comment by simonzack** [comment] 2015-01-27 19:38
Caused by the ternary matcher, should be fixed now.

**Closed by simonzack** 2015-01-27 19:38 UTC
